// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package job

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnspecified-0]
	_ = x[StatusNotStarted-1]
	_ = x[StatusRunning-2]
	_ = x[StatusComplete-3]
	_ = x[StatusStopped-4]
}

const _Status_name = "UnspecifiedNotStartedRunningCompleteStopped"

var _Status_index = [...]uint8{0, 11, 21, 28, 36, 43}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
