// Code generated by "stringer -type=JobStatus -trimprefix=JobStatus"; DO NOT EDIT.

package worker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JobStatusUnspecified-0]
	_ = x[JobStatusRunning-1]
	_ = x[JobStatusComplete-2]
	_ = x[JobStatusStopped-3]
}

const _JobStatus_name = "UnspecifiedRunningCompleteStopped"

var _JobStatus_index = [...]uint8{0, 11, 18, 26, 33}

func (i JobStatus) String() string {
	if i < 0 || i >= JobStatus(len(_JobStatus_index)-1) {
		return "JobStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
