---
name: Go
"on":
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install differ
        run: go install github.com/kevinburke/differ@1.2
      - name: Install wire
        run: go install github.com/google/wire/cmd/wire@v0.6.0
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.6.0
      - name: Install stringer
        run: go install golang.org/x/tools/cmd/stringer@v0.22.0
      - name: tidy
        run: differ go mod tidy
      - name: Generate
        run: |
          go generate ./...
          git checkout -- go.sum
          differ true
      - name: Format
        run: find . -name '*.go' -exec dirname {} \; | sort -u | xargs differ gofumpt -w -d
      - name: Build
        run: go build -v ./...
      - name: Test
        run: sudo go test -race -v ./...
